import datetime as dt
import uuid

from fastapi import HTTPException
from fastapi.params import (
    Depends,
    Header,
)
from sqlalchemy.orm import Session
from sqlalchemy.orm.exc import (
    NoResultFound,
)

from src.database import models
from src.database.session import get_session
from src.models.token import Token

DEFAULT_TTL_IN_S = 600

class SessionManager:
    """ Handle a credentials token for a user:
            as i didn't took time to implement a refresh token call from the front,
                i removed the logic relative to a token ttl

        TODO:
            with more time:
                - do not store the token in a db which is slow to be read but in a
                    reddis or something like that
                - use 3rd party for security (oauth/2)
                - not link a token to a user id but to a set of rights
    """
    def __init__(self, session: Session = Depends(get_session)):
        self.session = session

    def generate_token_for_user(self, user_id: int) -> Token:
        """ Use a user id to create a token around it,
                so a user can validate POST request without using their pass/login each time

            Args:
                user_id: the user the token is created for.
        """
        try:
            db_token: models.Token = (
                self.session.query(models.Token)
                    .filter(models.Token.user_id == user_id)
                    .one()
            )
        except NoResultFound:
            db_token: models.Token = models.Token(
                value=str(uuid.uuid4()),
                user_id=user_id,
                ttl=DEFAULT_TTL_IN_S,
                created_at=dt.datetime.now()
            )
            self.session.add(db_token)
            self.session.commit()
            self.session.refresh(db_token)
        return Token.from_orm(db_token)

    @staticmethod
    def require_authentication(
            session: Session = Depends(get_session),
            authorization: str = Header(...)
    ) -> int:
        """ Used as a route dependency,
                verify for the presence of a Bearer token and get the identity of the relevant user

            Args:
                session: dependency, a temporary session on the local db
                authorization: a bearer token, possibly generated by the other (non static) method
        """
        if not authorization:
            raise HTTPException(status_code=401, detail="you may not use this resource")

        try:
            db_token: models.Token = (
                session.query(models.Token)
                    .filter(models.Token.value == authorization[len("Bearer "):])
                    .one()
            )
        except NoResultFound:
            raise HTTPException(status_code=401, detail="Invalid Token, No user found.")
        else:
            return db_token.user_id
